"""create materials and material orders

Revision ID: 58382dfd1c4b
Revises: 73bb768b6560
Create Date: 2026-10-04 20:02:46.804792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58382dfd1c4b'
down_revision: Union[str, Sequence[str], None] = '73bb768b6560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordered_from', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'on_the_way', 'delivered', name='material_order_status'), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ordered_from'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_orders_id'), 'material_orders', ['id'], unique=False)
    op.create_index(op.f('ix_material_orders_ordered_from'), 'material_orders', ['ordered_from'], unique=False)
    op.create_table('materials',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('texture', sa.Enum('smooth', 'rough', name='material_texture'), nullable=False),
    sa.Column('pattern', sa.Enum('plain', 'patterned', name='material_pattern'), nullable=False),
    sa.Column('season', sa.Enum('summer', 'winter', 'all_seasons', 'spring', name='material_season'), nullable=False),
    sa.Column('stand', sa.Enum('stand', 'half_stand', 'loose', name='material_stand'), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('price >= 0.01', name='check_price_positive'),
    sa.ForeignKeyConstraint(['source_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_source_id'), 'materials', ['source_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('road_no', sa.Integer(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('building_no', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'BUSY', name='shop_status'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_materials_source_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_material_orders_ordered_from'), table_name='material_orders')
    op.drop_index(op.f('ix_material_orders_id'), table_name='material_orders')
    op.drop_table('material_orders')
    for t in ("material_order_status", "material_texture", "material_pattern", "material_season", "material_stand", "shop_status"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
    # ### end Alembic commands ###
