"""Add project models

Revision ID: 96d5a5d33209
Revises: 73bb768b6560
Create Date: 2026-10-04 20:26:49.545495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d5a5d33209'
down_revision: Union[str, Sequence[str], None] = '73bb768b6560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_measurements',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('neck', sa.Float(), nullable=False),
    sa.Column('chest', sa.Float(), nullable=False),
    sa.Column('arm', sa.Float(), nullable=False),
    sa.Column('shoulders', sa.Float(), nullable=False),
    sa.Column('waist', sa.Float(), nullable=False),
    sa.Column('wrist', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('hips', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_measurements_id'), 'client_measurements', ['id'], unique=False)
    op.create_table('materials',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('texture', sa.Enum('smooth', 'rough', name='material_texture'), nullable=False),
    sa.Column('pattern', sa.Enum('plain', 'patterned', name='material_pattern'), nullable=False),
    sa.Column('season', sa.Enum('summer', 'winter', 'all_seasons', 'spring', name='material_season'), nullable=False),
    sa.Column('stand', sa.Enum('stand', 'half_stand', 'loose', name='material_stand'), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('road_no', sa.Integer(), nullable=False),
    sa.Column('block_no', sa.Integer(), nullable=False),
    sa.Column('building_no', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('open', 'closed', 'busy', name='shop_status'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_table('thoub_orders',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('tailor_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('measurements_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'tailor_rejected', 'client_rejected', 'confirmed', 'in_progress', 'ready', 'on_the_way', 'delivered', 'canceled', name='order_status'), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('requested_deadline', sa.Date(), nullable=True),
    sa.Column('final_deadline', sa.Date(), nullable=True),
    sa.Column('material_amount', sa.Float(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['tailor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thoub_orders_id'), 'thoub_orders', ['id'], unique=False)
    op.create_table('material_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('thoub_order_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('expected_delivery_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'on_the_way', 'delivered', name='material_order_status'), server_default='pending', nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thoub_order_id'], ['thoub_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thoub_order_id')
    )
    op.create_index(op.f('ix_material_orders_id'), 'material_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_orders_id'), table_name='material_orders')
    op.drop_table('material_orders')
    op.drop_index(op.f('ix_thoub_orders_id'), table_name='thoub_orders')
    op.drop_table('thoub_orders')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_client_measurements_id'), table_name='client_measurements')
    op.drop_table('client_measurements')
    for t in ("material_order_status", "order_status", "shop_status", "material_texture", "material_pattern", "material_season", "material_stand"):
        op.execute(f"DROP TYPE IF EXISTS {t}")
    # ### end Alembic commands ###
