"""fix materials price and material order delivery date

Revision ID: c4930e29d13e
Revises: 96d5a5d33209
Create Date: 2026-10-05 12:36:21.042477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4930e29d13e'
down_revision: Union[str, Sequence[str], None] = '96d5a5d33209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_orders', 'expected_delivery_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.Date(),
               nullable=True)
    op.alter_column('materials', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.create_index(op.f('ix_materials_source_id'), 'materials', ['source_id'], unique=False)
    op.create_check_constraint('check_price_positive', 'materials', 'price >= 0.01')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_price_positive', 'materials', type_='check')
    op.drop_index(op.f('ix_materials_source_id'), table_name='materials')
    op.alter_column('materials', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('material_orders', 'expected_delivery_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###
